import { useState } from 'react';
import { CheckCircle2, CircleDashed, Download, Network, Search, ShieldAlert } from 'lucide-react';
import { Link } from 'react-router-dom';
import { projectsAPI } from '../services/api';
import { getErrorMessage } from '../services/errors';
import type { RDProject, WorkspaceSearchResult } from '../types';
import StatusMessage from './StatusMessage';

const labels:Record<string,string>={formulations:'Formulations',laboratory_results:'Laboratory',sensory_studies:'Sensory',experimental_plans:'Protocols',pilot_batches:'Pilot batches',stability_programs:'Stability',product_specifications:'Specifications',documents:'Documents',packaging_configurations:'Packaging',production_trials:'Production',qc_releases:'QC decisions',quality_events:'Quality events',capa_actions:'CAPA'};
export default function ProductPassportWorkspace({project}:{project:RDProject}){
  const passport=project.product_passport;const[query,setQuery]=useState('');const[results,setResults]=useState<WorkspaceSearchResult[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  if(!passport)return <div className="rounded-2xl border border-dashed border-slate-200 py-12 text-center"><Network className="mx-auto h-9 w-9 text-sky-400"/><h3 className="mt-3 font-black">Passport not available</h3><p className="mt-1 text-sm text-slate-500">Refresh this project to calculate its cross-domain evidence view.</p></div>;
  async function search(event:React.FormEvent){event.preventDefault();if(query.trim().length<2)return;setBusy(true);setError('');try{const response=await projectsAPI.searchWorkspace(query.trim());setResults(response.data.data);}catch(cause){setError(getErrorMessage(cause,'Workspace search is unavailable.'));}finally{setBusy(false);}}
  function download(){const blob=new Blob([JSON.stringify(passport,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${project.code}-product-passport.json`;anchor.click();URL.revokeObjectURL(url);}
  return <div className="space-y-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="eyebrow">Product Digital Passport</p><h3 className="mt-1 text-xl font-black">Evidence map for {project.code}</h3><p className="mt-1 max-w-3xl text-sm text-slate-500">A read-only view calculated from exact formulation versions, controlled evidence and release records.</p></div><button type="button" className="secondary-button" onClick={download}><Download className="h-4 w-4"/>Export JSON</button></div>
    <div className="grid gap-4 lg:grid-cols-[16rem_minmax(0,1fr)]"><article className={`rounded-2xl border p-5 ${passport.readiness.status==='blocked'?'border-rose-200 bg-rose-50':'border-sky-200 bg-sky-50'}`}><p className="eyebrow">Evidence readiness</p><strong className="mt-2 block text-4xl text-slate-950">{passport.readiness.score_percent}%</strong><p className="mt-1 text-sm font-bold capitalize text-slate-700">{passport.readiness.status.replaceAll('_',' ')}</p><p className="mt-3 text-xs text-slate-600">{passport.readiness.passed_gates} of {passport.readiness.total_gates} evidence gates passed</p></article><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{passport.readiness.gates.map(gate=><div key={gate.key} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3">{gate.passed?<CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600"/>:<CircleDashed className="h-5 w-5 shrink-0 text-amber-500"/>}<span className="text-sm font-bold text-slate-700">{gate.label}</span></div>)}</div></div>
    <section><div className="flex items-end justify-between"><div><h4 className="font-black">Traceability graph</h4><p className="mt-1 text-sm text-slate-500">{passport.graph.node_count} controlled records · {passport.graph.edge_count} explicit evidence links</p></div></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(passport.summary).map(([key,value])=><div key={key} className="rounded-xl border border-slate-200 bg-white p-3"><strong className="text-xl text-sky-700">{value}</strong><span className="ml-2 text-xs font-bold text-slate-500">{labels[key]||key}</span></div>)}</div><div className="mt-3 max-h-64 overflow-auto rounded-2xl border border-slate-200"><table className="min-w-full text-sm"><thead className="sticky top-0 bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-3 py-2">Source</th><th className="px-3 py-2">Relationship</th><th className="px-3 py-2">Target</th></tr></thead><tbody className="divide-y">{passport.graph.edges.slice(0,100).map((edge,index)=><tr key={`${edge.from}-${edge.to}-${index}`}><td className="px-3 py-2 font-mono text-xs">{edge.from}</td><td className="px-3 py-2 font-bold text-sky-700">{edge.relation}</td><td className="px-3 py-2 font-mono text-xs">{edge.to}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-2xl border border-slate-200 p-4"><h4 className="font-black">Structured workspace search</h4><p className="mt-1 text-sm text-slate-500">Searches controlled metadata in your workspace only. Raw payloads and extracted document text are excluded.</p><form onSubmit={search} className="mt-3 flex gap-2"><label className="flex-1"><span className="sr-only">Search workspace records</span><input value={query} minLength={2} maxLength={100} onChange={event=>setQuery(event.target.value)} placeholder="Project, formula, batch, document or quality event…"/></label><button className="primary-button" disabled={busy||query.trim().length<2}><Search className="h-4 w-4"/>{busy?'Searching…':'Search'}</button></form><StatusMessage error={error}/>{results.length>0&&<div className="mt-3 divide-y rounded-xl border border-slate-200">{results.map(item=><div key={`${item.type}-${item.id}`} className="flex items-center justify-between gap-3 p-3"><div><p className="text-xs font-black uppercase text-sky-700">{item.type.replaceAll('_',' ')}</p><strong className="text-sm">{item.title}</strong><p className="text-xs text-slate-500">{item.subtitle}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black uppercase text-slate-600">{item.status}</span><Link className="secondary-button !px-3 !py-1.5 text-xs" to={item.route}>Open</Link></div></div>)}</div>}</section>
    <div className="flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-900"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0"/><span>{passport.limitations[0]}</span></div><p className="text-[11px] text-slate-400">Engine {passport.engine_version} · generated {new Date(passport.generated_at).toLocaleString()}</p></div>;
}
