import { useMemo, useState } from 'react';
import { Beaker, CalendarCheck, CheckCircle2, ClipboardList, Download, Factory, Flag, FlaskConical, GitCommitHorizontal, Package, Plus, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { projectsAPI } from '../services/api';
import { getErrorMessage } from '../services/errors';
import type { RDDesignAnalysis, RDExperimentalPlan, RDPilotBatch, RDProject, RDProjectDecision, RDProjectMilestone } from '../types';
import StatusMessage from './StatusMessage';
import StabilityWorkspace from './StabilityWorkspace';
import SupplyChainWorkspace from './SupplyChainWorkspace';

type Tab = 'experiments' | 'doe' | 'batches' | 'stability' | 'supply' | 'milestones' | 'decisions' | 'timeline';
const csv = (value: string) => value.split(',').map(item => item.trim()).filter(Boolean);
const lines = (value: string) => value.split('\n').map(item => item.trim()).filter(Boolean);
const tabs: Array<{ key: Tab; label: string; icon: typeof Beaker }> = [
  { key: 'experiments', label: 'Experimental plans', icon: Beaker },
  { key: 'doe', label: 'DOE & next run', icon: FlaskConical },
  { key: 'batches', label: 'Pilot batches', icon: Factory },
  { key: 'stability', label: 'Stability & specs', icon: FlaskConical },
  { key: 'supply', label: 'Supply & packaging', icon: Package },
  { key: 'milestones', label: 'Milestones', icon: Flag },
  { key: 'decisions', label: 'Go / No-Go', icon: ShieldCheck },
  { key: 'timeline', label: 'Timeline', icon: GitCommitHorizontal },
];

export default function ProjectExecutionWorkspace({ project, onRefresh }: { project: RDProject; onRefresh: () => Promise<void> }) {
  const [tab, setTab] = useState<Tab>('experiments');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const trace = project.traceability;
  const plans = trace?.experimental_plans || [];
  const batches = trace?.pilot_batches || [];
  const milestones = trace?.milestones || [];
  const decisions = trace?.decisions || [];

  if (project.execution_available === false) return <section className="surface-card border-amber-200 bg-amber-50"><p className="eyebrow text-amber-700">R&D execution</p><h2 className="mt-1 text-lg font-black text-amber-950">Execution storage requires migration</h2><p className="mt-2 text-sm text-amber-900">Apply the pending Supabase R&D execution migration. Existing projects and briefs remain available.</p></section>;

  async function perform(action: () => Promise<unknown>, success: string) {
    setBusy(true); setError(''); setMessage('');
    try { await action(); setMessage(success); await onRefresh(); }
    catch (cause) { setError(getErrorMessage(cause, 'The project operation could not be saved.')); }
    finally { setBusy(false); }
  }

  return <section className="surface-card overflow-hidden p-0">
    <div className="flex flex-col gap-4 border-b border-slate-200 px-5 py-5 lg:flex-row lg:items-center lg:justify-between">
      <div><p className="eyebrow">Closed-loop execution</p><h2 className="mt-1 text-xl font-black text-slate-950">R&D experimental workspace</h2><p className="mt-1 text-sm text-slate-500">Every protocol, batch, gate and decision remains tied to {project.code}.</p></div>
      <div className="grid grid-cols-4 gap-2 text-center text-xs"><Metric value={plans.length} label="Plans"/><Metric value={batches.length} label="Batches"/><Metric value={milestones.length} label="Gates"/><Metric value={decisions.length} label="Decisions"/></div>
    </div>
    <div className="border-b border-slate-200 bg-slate-50/70 px-3 py-2"><div className="flex gap-2 overflow-x-auto" role="tablist" aria-label="Project execution sections">{tabs.map(item => { const Icon = item.icon; return <button key={item.key} type="button" role="tab" aria-selected={tab === item.key} onClick={() => setTab(item.key)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold transition ${tab === item.key ? 'bg-white text-sky-700 shadow-sm ring-1 ring-sky-200' : 'text-slate-500 hover:bg-white hover:text-slate-800'}`}><Icon className="h-4 w-4"/>{item.label}</button>; })}</div></div>
    <div className="p-5"><StatusMessage error={error} message={message}/>
      {tab === 'experiments' && <ExperimentalPlans project={project} plans={plans} busy={busy} perform={perform}/>} 
      {tab === 'doe' && <DoeWorkspace project={project} plans={plans} batches={batches} busy={busy} perform={perform}/>}
      {tab === 'batches' && <PilotBatches project={project} plans={plans} batches={batches} busy={busy} perform={perform}/>} 
      {tab === 'stability' && <StabilityWorkspace project={project} busy={busy} perform={perform}/>}
      {tab === 'supply' && <SupplyChainWorkspace project={project} onRefresh={onRefresh}/>}
      {tab === 'milestones' && <Milestones project={project} milestones={milestones} busy={busy} perform={perform}/>} 
      {tab === 'decisions' && <Decisions project={project} milestones={milestones} decisions={decisions} busy={busy} perform={perform}/>} 
      {tab === 'timeline' && <Timeline project={project}/>} 
    </div>
  </section>;
}

function ExperimentalPlans({ project, plans, busy, perform }: { project: RDProject; plans: RDExperimentalPlan[]; busy: boolean; perform: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const versions = project.traceability?.formulations || [];
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ name: '', objective: '', hypothesis: '', formulation_version_id: versions[0]?.id || '', method: 'Controlled comparative pilot', variables: '', controls: 'Reference formulation', steps: '', criteria: project.success_criteria?.join('\n') || '', planned_runs: '1', due_date: '' });
  async function submit(event: React.FormEvent) { event.preventDefault(); await perform(() => projectsAPI.createExperimentalPlan(project.id, { name: form.name, objective: form.objective, hypothesis: form.hypothesis, formulation_version_id: form.formulation_version_id, planned_runs: Number(form.planned_runs), due_date: form.due_date || null, status: 'draft', protocol: { method: form.method, variables: csv(form.variables), controls: lines(form.controls), procedure_steps: lines(form.steps), acceptance_criteria: lines(form.criteria) } }), 'Experimental plan saved with its exact formulation version.'); setOpen(false); }
  return <div className="space-y-4">
    <SectionHeading title="Controlled experimental plans" description="Define the hypothesis, controlled variables, reproducible procedure and measurable acceptance criteria." action={versions.length ? <button type="button" onClick={() => setOpen(!open)} className="primary-button"><Plus className="h-4 w-4"/>New plan</button> : <Link to="/formulations" className="primary-button">Create formulation version</Link>}/>
    {project.brief_status !== 'validated' && <Notice text="The structured brief must be validated before an experimental plan can be created."/>}
    {open && <form onSubmit={submit} className="rounded-2xl border border-sky-200 bg-sky-50/50 p-4"><div className="grid gap-4 md:grid-cols-2"><Field label="Plan name"><input required minLength={3} value={form.name} onChange={e => setForm({...form, name: e.target.value})}/></Field><Field label="Exact formulation version"><select required value={form.formulation_version_id} onChange={e => setForm({...form, formulation_version_id: e.target.value})}><option value="">Choose a version</option>{versions.map(version => <option key={version.id} value={version.id}>{version.name} · v{version.version} · {version.code}</option>)}</select></Field><Field label="Decision objective" wide><textarea required minLength={10} rows={2} value={form.objective} onChange={e => setForm({...form, objective: e.target.value})}/></Field><Field label="Testable hypothesis" wide><textarea required minLength={10} rows={2} value={form.hypothesis} onChange={e => setForm({...form, hypothesis: e.target.value})}/></Field><Field label="Method"><input required value={form.method} onChange={e => setForm({...form, method: e.target.value})}/></Field><Field label="Variables (comma separated)"><input required value={form.variables} onChange={e => setForm({...form, variables: e.target.value})} placeholder="Citric acid %, pasteurization temperature"/></Field><Field label="Controls (one per line)"><textarea rows={3} value={form.controls} onChange={e => setForm({...form, controls: e.target.value})}/></Field><Field label="Procedure steps (one per line)"><textarea required rows={3} value={form.steps} onChange={e => setForm({...form, steps: e.target.value})} placeholder={'Prepare ingredients\nMix for 10 minutes\nPasteurize and fill'}/></Field><Field label="Acceptance criteria (one per line)" wide><textarea required rows={3} value={form.criteria} onChange={e => setForm({...form, criteria: e.target.value})}/></Field><Field label="Planned runs"><input type="number" min="1" max="100" required value={form.planned_runs} onChange={e => setForm({...form, planned_runs: e.target.value})}/></Field><Field label="Due date"><input type="date" value={form.due_date} onChange={e => setForm({...form, due_date: e.target.value})}/></Field></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="secondary-button">Cancel</button><button disabled={busy || project.brief_status !== 'validated'} className="primary-button">Save protocol</button></div></form>}
    {plans.length === 0 ? <Empty icon={Beaker} title="No experimental plan yet" text="Create the first reproducible protocol from a validated brief and an exact formulation version."/> : <div className="grid gap-3 lg:grid-cols-2">{plans.map(plan => <article key={plan.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">{versionLabel(project, plan.formulation_version_id)}</p><h3 className="mt-1 font-black text-slate-950">{plan.name}</h3></div><Status value={plan.status}/></div><p className="mt-3 text-sm text-slate-600">{plan.hypothesis}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Mini value={plan.planned_runs} label="Runs"/><Mini value={plan.protocol.variables.length} label="Variables"/><Mini value={plan.protocol.acceptance_criteria.length} label="Criteria"/></div><label className="mt-4 block text-xs font-bold text-slate-500">Plan status<select value={plan.status} disabled={busy} onChange={e => void perform(() => projectsAPI.updateExperimentalPlan(project.id, plan.id, { status: e.target.value }), 'Experimental plan status updated.')} className="mt-1"><option value="draft">Draft</option><option value="ready">Ready</option><option value="running">Running</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label></article>)}</div>}
  </div>;
}

function DoeWorkspace({ project, plans, batches, busy, perform }: { project: RDProject; plans: RDExperimentalPlan[]; batches: RDPilotBatch[]; busy: boolean; perform: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const [planId, setPlanId] = useState(plans[0]?.id || '');
  const [analysis, setAnalysis] = useState<RDDesignAnalysis | null>(null);
  const [analysisError, setAnalysisError] = useState('');
  const [form, setForm] = useState({ type: 'full_factorial', factors: 'acid | Citric acid | 0.10 | 0.30 | %\ntemperature | Pasteurization temperature | 75 | 85 | °C', responses: 'stability | Stability score | maximize | | /10', center_points: '1', replicates: '1' });
  const plan = plans.find(item => item.id === planId);
  const linkedBatches = batches.filter(item => item.experimental_plan_id === planId && item.doe_run_id);
  const completedRuns = new Set(linkedBatches.map(item => item.doe_run_id));
  const parseFactors = () => lines(form.factors).map(line => { const [key, label, low, high, unit = ''] = line.split('|').map(value => value.trim()); return { key, label, low: Number(low), high: Number(high), unit }; });
  const parseResponses = () => lines(form.responses).map(line => { const [key, label, goal, target, unit = ''] = line.split('|').map(value => value.trim()); return { key, label, goal, ...(target ? { target: Number(target) } : {}), unit }; });
  async function generate() {
    if (!plan) return;
    await perform(() => projectsAPI.generateDoeDesign(project.id, plan.id, { type: form.type, factors: parseFactors(), responses: parseResponses(), center_points: Number(form.center_points), replicates: Number(form.replicates) }), 'Deterministic DOE matrix generated and signed.');
    setAnalysis(null);
  }
  async function loadAnalysis() {
    if (!plan) return;
    setAnalysisError('');
    try { const response = await projectsAPI.getDoeAnalysis(project.id, plan.id); setAnalysis(response.data.data); }
    catch (cause) { setAnalysisError(getErrorMessage(cause, 'DOE analysis is not available.')); }
  }
  async function exportReport() {
    if (!plan) return;
    setAnalysisError('');
    try {
      const response = await projectsAPI.exportDoeReport(project.id, plan.id);
      const url = URL.createObjectURL(response.data); const anchor = document.createElement('a');
      anchor.href = url; anchor.download = `${project.code}-${plan.name}`.replace(/[^a-z0-9-]+/gi, '-').toLowerCase() + '-doe.csv'; anchor.click(); URL.revokeObjectURL(url);
    } catch (cause) { setAnalysisError(getErrorMessage(cause, 'DOE report could not be downloaded.')); }
  }
  return <div className="space-y-5">
    <SectionHeading title="Deterministic design of experiments" description="Generate a signed design matrix, record each run as a pilot batch, then calculate screening effects only from measured results."/>
    {!plans.length ? <Empty icon={FlaskConical} title="No experimental plan available" text="Create a controlled plan before generating a DOE matrix."/> : <>
      <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_18rem]"><div className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-4 md:grid-cols-2"><Field label="Experimental plan" wide><select value={planId} onChange={event => { setPlanId(event.target.value); setAnalysis(null); }}>{plans.map(item => <option key={item.id} value={item.id}>{item.name} · {versionLabel(project, item.formulation_version_id)}</option>)}</select></Field><Field label="Design"><select value={form.type} disabled={Boolean(plan?.design && linkedBatches.length)} onChange={event => setForm({...form, type: event.target.value})}><option value="full_factorial">Full factorial (2 levels)</option><option value="response_surface">Face-centred response surface</option></select></Field><Field label="Replicates"><input type="number" min="1" max="5" value={form.replicates} onChange={event => setForm({...form, replicates: event.target.value})}/></Field><Field label="Factors — key | label | low | high | unit" wide><textarea rows={4} value={form.factors} onChange={event => setForm({...form, factors: event.target.value})}/></Field><Field label="Responses — key | label | goal | target | unit" wide><textarea rows={3} value={form.responses} onChange={event => setForm({...form, responses: event.target.value})}/><span className="mt-1 block text-xs text-slate-500">Goals: maximize, minimize or target. A numeric target is mandatory for target.</span></Field><Field label="Centre points"><input type="number" min="0" max="10" value={form.center_points} onChange={event => setForm({...form, center_points: event.target.value})}/></Field></div><div className="mt-4 flex flex-wrap justify-end gap-2"><button type="button" disabled={busy || Boolean(plan?.design && linkedBatches.length)} onClick={() => void generate()} className="primary-button">{plan?.design ? 'Regenerate design' : 'Generate design'}</button><button type="button" disabled={!plan?.design} onClick={() => void loadAnalysis()} className="secondary-button">Refresh analysis</button><button type="button" disabled={!plan?.design} onClick={() => void exportReport()} className="secondary-button"><Download className="h-4 w-4"/>Export DOE</button></div></div>
      <aside className="rounded-2xl border border-sky-200 bg-sky-50 p-4"><p className="eyebrow !text-sky-800">Scientific guardrail</p><h4 className="mt-2 font-black text-slate-950">Screening, not automatic proof</h4><p className="mt-2 text-sm leading-6 text-slate-700">The engine never invents observations or p-values. The next run is selected only from this signed matrix and the responses recorded in completed pilot batches.</p>{plan?.design && <div className="mt-4 grid grid-cols-2 gap-2"><Mini value={plan.design.run_count} label="Designed runs"/><Mini value={completedRuns.size} label="Linked runs"/></div>}</aside></div>
      {analysisError && <Notice text={analysisError}/>}
      {plan?.design && <div className="overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Run</th>{plan.design.factors.map(factor => <th key={factor.key} className="px-3 py-3">{factor.label}</th>)}<th className="px-3 py-3">Execution</th></tr></thead><tbody className="divide-y">{plan.design.runs.map(run => <tr key={run.id}><td className="px-3 py-3 font-mono text-xs">{run.id}</td>{plan.design!.factors.map(factor => <td key={factor.key} className="px-3 py-3 font-semibold">{run.factor_settings[factor.key].value} {factor.unit}</td>)}<td className="px-3 py-3"><Status value={completedRuns.has(run.id) ? 'completed' : 'planned'}/></td></tr>)}</tbody></table></div>}
      {analysis && <><div className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 p-4"><p className="eyebrow">Recorded-data analysis</p><div className="mt-3 grid grid-cols-3 gap-2"><Mini value={analysis.observation_count} label="Observations"/><Mini value={analysis.completed_run_count} label="Executed"/><Mini value={analysis.remaining_run_count} label="Remaining"/></div><div className="mt-4 space-y-2">{Object.entries(analysis.models).map(([key, model]) => <div key={key} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-3"><strong>{key}</strong><Status value={model.status === 'fitted' ? 'completed' : 'draft'}/></div>{model.diagnostics ? <><p className="mt-1 text-xs text-slate-600">R² {model.diagnostics.r_squared} · RMSE {model.diagnostics.rmse} · residual df {model.diagnostics.residual_degrees_of_freedom} · model p {model.anova?.p_value ?? 'not evaluable'}</p>{model.lack_of_fit && <p className="mt-2 text-xs leading-5 text-slate-600">Pure-error df {model.lack_of_fit.pure_error_degrees_of_freedom} · lack-of-fit p {model.lack_of_fit.p_value ?? 'not evaluable'}<br/>{model.lack_of_fit.conclusion}</p>}</> : <p className="mt-1 text-xs text-slate-500">{model.observations}/{model.required || '—'} observations available</p>}</div>)}</div><div className={`mt-4 rounded-xl p-3 text-xs leading-5 ${analysis.applicability.inferential_claims_allowed ? 'bg-emerald-50 text-emerald-900' : 'bg-amber-50 text-amber-900'}`}><strong>{analysis.applicability.inferential_claims_allowed ? 'Inferential checks available' : 'Inference blocked'}</strong><br/>{analysis.applicability.reason}</div></article><article className="rounded-2xl border border-sky-200 bg-sky-50 p-4"><p className="eyebrow !text-sky-800">Next controlled run</p>{analysis.next_run ? <><h4 className="mt-2 text-lg font-black text-slate-950">{analysis.next_run.run_id}</h4><p className="mt-1 text-sm text-slate-700">Basis: {analysis.next_run.basis.replace(/_/g, ' ')}</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(analysis.next_run.factor_settings).map(([key, item]) => <span key={key} className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-700 ring-1 ring-sky-200">{key}: {item.value} {item.unit}</span>)}</div><p className="mt-4 text-xs leading-5 text-amber-900">{analysis.next_run.warning}</p></> : <p className="mt-3 text-sm text-emerald-800">All designed runs have recorded observations.</p>}</article></div>{Object.entries(analysis.models).map(([key, model]) => model.surface ? <SurfacePreview key={key} response={key} surface={model.surface}/> : null)}</>}
    </>}
  </div>;
}

function SurfacePreview({ response, surface }: { response: string; surface: NonNullable<NonNullable<RDDesignAnalysis['models'][string]['surface']>> }) {
  const values = surface.points.map(point => point.prediction); const minimum = Math.min(...values); const maximum = Math.max(...values); const span = maximum - minimum || 1;
  return <article className="rounded-2xl border border-slate-200 p-4"><p className="eyebrow">Predicted response surface</p><h4 className="mt-1 font-black text-slate-950">{response} · {surface.x_factor.label}{surface.y_factor ? ` × ${surface.y_factor.label}` : ''}</h4><p className="mt-1 text-xs text-slate-500">Model prediction grid only. Fixed factors are held at their centre level.</p><div className={`mt-4 grid gap-1 ${surface.kind === 'surface' ? 'grid-cols-9' : 'grid-cols-9'}`}>{surface.points.map((point, index) => { const intensity = (point.prediction - minimum) / span; return <div key={`${point.x}-${point.y}-${index}`} title={`${surface.x_factor.label}: ${point.x}; ${surface.y_factor?.label || response}: ${point.y ?? point.prediction}; predicted ${response}: ${point.prediction}`} className="flex aspect-square min-h-8 items-center justify-center rounded text-[9px] font-bold" style={{ backgroundColor: `hsl(${205 - intensity * 65} 80% ${94 - intensity * 35}%)`, color: intensity > 0.58 ? 'white' : '#0f172a' }}>{point.prediction}</div>; })}</div><div className="mt-3 flex justify-between text-xs font-semibold text-slate-500"><span>Low prediction {minimum}</span><span>High prediction {maximum}</span></div></article>;
}

function PilotBatches({ project, plans, batches, busy, perform }: { project: RDProject; plans: RDExperimentalPlan[]; batches: RDPilotBatch[]; busy: boolean; perform: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ experimental_plan_id: plans[0]?.id || '', doe_run_id: '', batch_code: '', batch_size_liters: '20', scheduled_at: '', procedure_notes: '', deviations: '' });
  const selectedPlan = plans.find(plan => plan.id === form.experimental_plan_id);
  const usedRuns = new Set(batches.filter(item => item.experimental_plan_id === selectedPlan?.id).map(item => item.doe_run_id));
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!selectedPlan) return; await perform(() => projectsAPI.createPilotBatch(project.id, selectedPlan.id, { batch_code: form.batch_code, formulation_version_id: selectedPlan.formulation_version_id, batch_size_liters: Number(form.batch_size_liters), scheduled_at: form.scheduled_at ? new Date(form.scheduled_at).toISOString() : null, status: 'planned', actual_quantities: [], procedure_notes: form.procedure_notes, deviations: lines(form.deviations), observations: '', conclusion: '', ...(form.doe_run_id ? { doe_run_id: form.doe_run_id } : {}) }), 'Pilot batch created from the controlled protocol.'); setOpen(false); }
  return <div className="space-y-4"><SectionHeading title="Pilot batch execution" description="Schedule physical runs and preserve the exact formulation version, quantities, lots, deviations and conclusions." action={<button type="button" disabled={!plans.length} onClick={() => setOpen(!open)} className="primary-button"><Plus className="h-4 w-4"/>New pilot batch</button>}/>{!plans.length && <Notice text="Create an experimental plan before scheduling a pilot batch."/>}
    {open && <form onSubmit={submit} className="rounded-2xl border border-sky-200 bg-sky-50/50 p-4"><div className="grid gap-4 md:grid-cols-2"><Field label="Experimental plan"><select required value={form.experimental_plan_id} onChange={e => setForm({...form, experimental_plan_id: e.target.value, doe_run_id: ''})}>{plans.map(plan => <option key={plan.id} value={plan.id}>{plan.name} · {versionLabel(project, plan.formulation_version_id)}</option>)}</select></Field><Field label="DOE run (optional)"><select value={form.doe_run_id} onChange={e => setForm({...form, doe_run_id: e.target.value})}><option value="">Standalone controlled batch</option>{selectedPlan?.design?.runs.filter(run => !usedRuns.has(run.id)).map(run => <option key={run.id} value={run.id}>{run.id} · order {run.standard_order}</option>)}</select></Field><Field label="Batch code"><input required minLength={2} value={form.batch_code} onChange={e => setForm({...form, batch_code: e.target.value})} placeholder="PILOT-2026-001"/></Field><Field label="Batch size (L)"><input required type="number" min="0.01" step="0.01" value={form.batch_size_liters} onChange={e => setForm({...form, batch_size_liters: e.target.value})}/></Field><Field label="Scheduled date and time"><input type="datetime-local" value={form.scheduled_at} onChange={e => setForm({...form, scheduled_at: e.target.value})}/></Field><Field label="Execution notes" wide><textarea rows={3} value={form.procedure_notes} onChange={e => setForm({...form, procedure_notes: e.target.value})}/></Field></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="secondary-button">Cancel</button><button disabled={busy} className="primary-button">Create batch</button></div></form>}
    {batches.length === 0 ? <Empty icon={Factory} title="No pilot batch yet" text="A pilot batch is created from a controlled experimental plan, never as an orphan record."/> : <div className="space-y-3">{batches.map(batch => <PilotBatchRecord key={batch.id} project={project} plan={plans.find(plan => plan.id === batch.experimental_plan_id)} batch={batch} busy={busy} perform={perform}/>)}</div>}
  </div>;
}

function PilotBatchRecord({ project, plan, batch, busy, perform }: { project: RDProject; plan?: RDExperimentalPlan; batch: RDPilotBatch; busy: boolean; perform: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ status: batch.status, produced_at: batch.produced_at?.slice(0, 16) || '', procedure_notes: batch.procedure_notes || '', deviations: batch.deviations.join('\n'), observations: batch.observations || '', conclusion: batch.conclusion || '', quantities: batch.actual_quantities.map(item => `${item.material_name} | ${item.quantity} | ${item.unit} | ${item.lot_code}`).join('\n'), responses: Object.entries(batch.response_values || {}).map(([key, value]) => `${key} | ${value}`).join('\n') });
  const parseQuantities = () => lines(form.quantities).map(line => { const [material_name, quantity, rawUnit, lot_code = ''] = line.split('|').map(value => value.trim()); const unit = rawUnit?.toLowerCase(); return { material_name, quantity: Number(quantity), unit, lot_code }; });
  const parseResponses = () => Object.fromEntries(lines(form.responses).map(line => { const [key, value] = line.split('|').map(item => item.trim()); return [key, Number(value)]; }));
  async function save() { await perform(() => projectsAPI.updatePilotBatch(project.id, batch.id, { status: form.status, produced_at: form.produced_at ? new Date(form.produced_at).toISOString() : null, actual_quantities: parseQuantities(), procedure_notes: form.procedure_notes, deviations: lines(form.deviations), observations: form.observations, conclusion: form.conclusion, ...(batch.doe_run_id ? { response_values: parseResponses() } : {}) }), 'Pilot batch execution record saved.'); setEditing(false); }
  return <article className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">{plan?.name || 'Controlled protocol'}</p><h3 className="mt-1 text-lg font-black text-slate-950">{batch.batch_code}</h3><p className="mt-1 text-sm text-slate-500">{versionLabel(project, batch.formulation_version_id)} · {batch.batch_size_liters} L</p></div><div className="flex items-center gap-2"><Status value={batch.status}/><button type="button" onClick={() => setEditing(!editing)} className="secondary-button">{editing ? 'Close' : 'Complete record'}</button></div></div>
    {!editing && <div className="mt-4 grid gap-2 sm:grid-cols-4"><Mini value={batch.actual_quantities.length} label="Actual weights"/><Mini value={batch.actual_quantities.filter(item => item.lot_code).length} label="Material lots"/><Mini value={batch.deviations.length} label="Deviations"/><Mini value={batch.conclusion ? 1 : 0} label="Conclusion"/></div>}
    {editing && <div className="mt-5 grid gap-4 border-t border-slate-100 pt-4 md:grid-cols-2"><Field label="Execution status"><select value={form.status} onChange={e => setForm({...form, status: e.target.value as RDPilotBatch['status']})}><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="rejected">Rejected</option></select></Field><Field label="Produced date and time"><input type="datetime-local" value={form.produced_at} onChange={e => setForm({...form, produced_at: e.target.value})}/></Field>{batch.doe_run_id && <Field label="Measured DOE responses — key | value" wide><textarea rows={3} value={form.responses} onChange={e => setForm({...form, responses: e.target.value})} placeholder={plan?.design?.responses.map(item => `${item.key} | `).join('\n')}/><span className="mt-1 block text-xs text-slate-500">Only responses declared in the signed design are accepted.</span></Field>}<Field label="Actual weights and material lots" wide><textarea rows={4} value={form.quantities} onChange={e => setForm({...form, quantities: e.target.value})} placeholder={'Material | quantity | kg | lot code\nWater | 18 | l | WATER-2409'}/><span className="mt-1 block text-xs text-slate-500">One line per material. Units accepted: g, kg, ml, l.</span></Field><Field label="Procedure notes" wide><textarea rows={3} value={form.procedure_notes} onChange={e => setForm({...form, procedure_notes: e.target.value})}/></Field><Field label="Deviations (one per line)"><textarea rows={3} value={form.deviations} onChange={e => setForm({...form, deviations: e.target.value})}/></Field><Field label="Observations"><textarea rows={3} value={form.observations} onChange={e => setForm({...form, observations: e.target.value})}/></Field><Field label="Batch conclusion" wide><textarea rows={3} value={form.conclusion} onChange={e => setForm({...form, conclusion: e.target.value})}/></Field><div className="flex justify-end md:col-span-2"><button type="button" onClick={() => void save()} disabled={busy} className="primary-button">Save execution record</button></div></div>}
  </article>;
}

function Milestones({ project, milestones, busy, perform }: { project: RDProject; milestones: RDProjectMilestone[]; busy: boolean; perform: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [form, setForm] = useState({ title: '', description: '', stage: project.stage, due_date: '', responsible: '', criteria: '' });
  async function submit(event: React.FormEvent) { event.preventDefault(); await perform(() => projectsAPI.createMilestone(project.id, { title: form.title, description: form.description, stage: form.stage, due_date: form.due_date || null, responsible: form.responsible, success_criteria: lines(form.criteria), status: 'planned' }), 'Project milestone saved.'); setOpen(false); }
  return <div className="space-y-4"><SectionHeading title="Measurable project gates" description="Plan the evidence required for each lifecycle gate and assign a clear owner and due date." action={<button type="button" onClick={() => setOpen(!open)} className="primary-button"><Plus className="h-4 w-4"/>New milestone</button>}/>{open && <form onSubmit={submit} className="rounded-2xl border border-sky-200 bg-sky-50/50 p-4"><div className="grid gap-4 md:grid-cols-2"><Field label="Milestone title"><input required value={form.title} onChange={e => setForm({...form, title: e.target.value})}/></Field><Field label="Lifecycle gate"><select value={form.stage} onChange={e => setForm({...form, stage: e.target.value as RDProject['stage']})}>{['brief','concept','formulation','laboratory','sensory','validation','industrialization','launched'].map(stage => <option key={stage}>{stage}</option>)}</select></Field><Field label="Responsible"><input value={form.responsible} onChange={e => setForm({...form, responsible: e.target.value})}/></Field><Field label="Due date"><input type="date" value={form.due_date} onChange={e => setForm({...form, due_date: e.target.value})}/></Field><Field label="Description" wide><textarea rows={2} value={form.description} onChange={e => setForm({...form, description: e.target.value})}/></Field><Field label="Success criteria (one per line)" wide><textarea required rows={3} value={form.criteria} onChange={e => setForm({...form, criteria: e.target.value})}/></Field></div><div className="mt-4 flex justify-end gap-2"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancel</button><button disabled={busy} className="primary-button">Save milestone</button></div></form>}
    {milestones.length === 0 ? <Empty icon={CalendarCheck} title="No milestone scheduled" text="Turn lifecycle stages into dated, measurable gates."/> : <div className="grid gap-3 md:grid-cols-2">{milestones.map(item => <article key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><p className="eyebrow">{item.stage}</p><h3 className="mt-1 font-black">{item.title}</h3></div><Status value={item.status}/></div><p className="mt-2 text-sm text-slate-500">{item.responsible || 'Unassigned'} · {item.due_date || 'No due date'}</p><p className="mt-2 text-xs text-slate-600">{item.success_criteria.length} measurable acceptance criteria</p><select className="mt-3" value={item.status} disabled={busy} onChange={e => void perform(() => projectsAPI.updateMilestone(project.id, item.id, { status: e.target.value }), 'Milestone status updated.')}><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="blocked">Blocked</option></select></article>)}</div>}
  </div>;
}

function Decisions({ project, milestones, decisions, busy, perform }: { project: RDProject; milestones: RDProjectMilestone[]; decisions: RDProjectDecision[]; busy: boolean; perform: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const versions = project.traceability?.formulations || []; const [open, setOpen] = useState(false); const [form, setForm] = useState({ title: '', outcome: 'go', rationale: '', evidence_refs: '', formulation_version_id: '', milestone_id: '' });
  async function submit(event: React.FormEvent) { event.preventDefault(); await perform(() => projectsAPI.recordDecision(project.id, { title: form.title, outcome: form.outcome, rationale: form.rationale, evidence_refs: lines(form.evidence_refs), formulation_version_id: form.formulation_version_id || null, milestone_id: form.milestone_id || null }), 'Immutable project decision recorded.'); setOpen(false); }
  return <div className="space-y-4"><SectionHeading title="Immutable Go / No-Go record" description="Record the evidence and rationale behind each material decision. Published decisions cannot be edited." action={<button type="button" onClick={() => setOpen(!open)} className="primary-button"><Plus className="h-4 w-4"/>Record decision</button>}/>{open && <form onSubmit={submit} className="rounded-2xl border border-sky-200 bg-sky-50/50 p-4"><div className="grid gap-4 md:grid-cols-2"><Field label="Decision title"><input required value={form.title} onChange={e => setForm({...form, title: e.target.value})}/></Field><Field label="Outcome"><select value={form.outcome} onChange={e => setForm({...form, outcome: e.target.value})}><option value="go">Go</option><option value="no_go">No-Go</option><option value="hold">Hold</option><option value="rework">Rework</option></select></Field><Field label="Exact formulation version"><select value={form.formulation_version_id} onChange={e => setForm({...form, formulation_version_id: e.target.value})}><option value="">Project-level decision</option>{versions.map(version => <option key={version.id} value={version.id}>{version.name} · v{version.version}</option>)}</select></Field><Field label="Milestone"><select value={form.milestone_id} onChange={e => setForm({...form, milestone_id: e.target.value})}><option value="">No milestone link</option>{milestones.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></Field><Field label="Evidence references (one per line)" wide><textarea required rows={3} value={form.evidence_refs} onChange={e => setForm({...form, evidence_refs: e.target.value})} placeholder={'LAB-2026-014\nSensory study S-006\nApproved specification rev. 2'}/></Field><Field label="Decision rationale" wide><textarea required minLength={10} rows={3} value={form.rationale} onChange={e => setForm({...form, rationale: e.target.value})}/></Field></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="secondary-button">Cancel</button><button disabled={busy} className="primary-button">Record immutable decision</button></div></form>}
    {decisions.length === 0 ? <Empty icon={ShieldCheck} title="No formal decision recorded" text="Record decisions only when their evidence and rationale are ready for the audit trail."/> : <div className="space-y-3">{decisions.map(item => <article key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">{new Date(item.decided_at).toLocaleString()}</p><h3 className="mt-1 font-black">{item.title}</h3></div><Status value={item.outcome}/></div><p className="mt-3 text-sm text-slate-700">{item.rationale}</p><div className="mt-3 flex flex-wrap gap-2">{item.evidence_refs.map(ref => <span key={ref} className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600">{ref}</span>)}</div><p className="mt-3 flex items-center gap-1 text-xs font-semibold text-slate-500"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-600"/>Append-only audit record</p></article>)}</div>}
  </div>;
}

function Timeline({ project }: { project: RDProject }) {
  const entries = useMemo(() => (project.events || []).map(event => ({ id: event.id, date: event.created_at, type: event.event_type, detail: event.details })).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()), [project.events]);
  return <div className="space-y-4"><SectionHeading title="Cross-domain project history" description="Material lifecycle, protocol, batch, milestone and decision events are attributed and timestamped."/>{entries.length === 0 ? <Empty icon={ClipboardList} title="No history yet" text="Material project events will appear here automatically."/> : <ol className="relative ml-3 border-l border-sky-200">{entries.map(entry => <li key={entry.id} className="mb-5 ml-5"><span className="absolute -left-2 flex h-4 w-4 rounded-full border-2 border-white bg-sky-500"/><p className="text-sm font-black capitalize text-slate-900">{entry.type.split('_').join(' ')}</p><time className="text-xs text-slate-500">{new Date(entry.date).toLocaleString()}</time><p className="mt-1 break-words font-mono text-[11px] text-slate-500">{Object.entries(entry.detail || {}).map(([key, value]) => `${key}: ${String(value)}`).join(' · ')}</p></li>)}</ol>}</div>;
}

function versionLabel(project: RDProject, id: string) { const version = project.traceability?.formulations.find(item => item.id === id); return version ? `${version.name} · v${version.version}` : 'Unknown version'; }
function SectionHeading({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-lg font-black text-slate-950">{title}</h3><p className="mt-1 max-w-3xl text-sm text-slate-500">{description}</p></div>{action}</div>; }
function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={wide ? 'md:col-span-2' : ''}><span>{label}</span>{children}</label>; }
function Metric({ value, label }: { value: number; label: string }) { return <div className="min-w-16 rounded-xl bg-slate-50 px-2 py-2"><strong className="block text-lg text-slate-950">{value}</strong><span className="text-slate-500">{label}</span></div>; }
function Mini({ value, label }: { value: number; label: string }) { return <div className="rounded-xl bg-slate-50 p-2"><strong className="block text-slate-900">{value}</strong><span className="text-[10px] text-slate-500">{label}</span></div>; }
function Status({ value }: { value: string }) { const good = ['go','completed','ready'].includes(value); const bad = ['no_go','rejected','blocked','cancelled'].includes(value); return <span className={`rounded-full px-2.5 py-1 text-xs font-black uppercase tracking-wide ${good ? 'bg-emerald-100 text-emerald-700' : bad ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'}`}>{value.replace('_', '-')}</span>; }
function Notice({ text }: { text: string }) { return <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-900">{text}</div>; }
function Empty({ icon: Icon, title, text }: { icon: typeof Beaker; title: string; text: string }) { return <div className="rounded-2xl border border-dashed border-slate-200 py-10 text-center"><Icon className="mx-auto h-8 w-8 text-sky-400"/><h4 className="mt-3 font-black text-slate-900">{title}</h4><p className="mx-auto mt-1 max-w-xl text-sm text-slate-500">{text}</p></div>; }
