import { useState } from 'react';
import { Activity, CheckCircle2, Clock3, LockKeyhole, Plus, Thermometer } from 'lucide-react';
import { projectsAPI } from '../services/api';
import { getErrorMessage } from '../services/errors';
import type { RDProductSpecification, RDProject, RDStabilityAnalysis, RDStabilityLimit } from '../types';

const lines = (value: string) => value.split('\n').map(item => item.trim()).filter(Boolean);
const csvNumbers = (value: string) => value.split(',').map(item => Number(item.trim())).filter(Number.isFinite);
const statusClass = (value: string) => value.includes('fail') ? 'bg-rose-100 text-rose-700' : value.includes('pass') || value === 'approved' || value === 'completed' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700';
const Badge = ({ value }: { value: string }) => <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wide ${statusClass(value)}`}>{value.replace(/_/g, ' ')}</span>;

function parseLimits(value: string): RDStabilityLimit[] {
  return lines(value).map(line => {
    const [key, label, source, unit = '', lower, upper, change] = line.split('|').map(item => item.trim());
    return { key, label, source: source as RDStabilityLimit['source'], unit, ...(lower ? { lower: Number(lower) } : {}), ...(upper ? { upper: Number(upper) } : {}), ...(change ? { max_change_from_baseline: Number(change) } : {}) };
  });
}

export default function StabilityWorkspace({ project, busy, perform }: { project: RDProject; busy: boolean; perform: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const trace = project.traceability;
  const programs = trace?.stability_programs || []; const observations = trace?.stability_observations || []; const specifications = trace?.product_specifications || [];
  const versions = trace?.formulations || []; const laboratory = trace?.laboratory_results || [];
  const [programOpen, setProgramOpen] = useState(false); const [specOpen, setSpecOpen] = useState(false);
  const [programId, setProgramId] = useState(programs[0]?.id || ''); const program = programs.find(item => item.id === programId) || programs[0];
  const [analysis, setAnalysis] = useState<RDStabilityAnalysis | null>(null); const [error, setError] = useState('');
  const [programForm, setProgramForm] = useState({ name: '', formulation_version_id: versions[0]?.id || '', protocol: 'Store sealed finished-product packs under controlled conditions and test each declared timepoint.', conditions: 'ambient | Ambient dark | 25 | 60 | dark\naccelerated | Accelerated dark | 40 | 75 | dark', timepoints: '0, 30, 60, 90', replicates: '1', parameters: 'ph | Finished product pH | measurements | pH | 2.8 | 3.5 | 0.20\nturbidity | Turbidity | measurements | NTU | | 20 | 10\noverall_acceptance | Overall acceptance | sensory | /10 | 7 | | 1' });
  const [observationForm, setObservationForm] = useState({ laboratory_result_id: '', condition_id: '', timepoint_days: '', replicate: '1' });
  const [specForm, setSpecForm] = useState({ name: '', formulation_version_id: versions[0]?.id || '', markets: project.target_market || 'Algeria', effective_date: '', notes: '', limits: 'ph | Finished product pH | measurements | pH | 2.8 | 3.5 |\nturbidity | Turbidity | measurements | NTU | | 20 |\noverall_acceptance | Overall acceptance | sensory | /10 | 7 | |' });
  const [approval, setApproval] = useState({ specification_id: '', rationale: '', evidence_refs: '' });

  if (project.stability_available === false) return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-black text-amber-950">Stability storage requires migration</h3><p className="mt-2 text-sm text-amber-900">Apply the pending Supabase stability and specifications migration before using this workspace.</p></div>;

  async function createProgram(event: React.FormEvent) {
    event.preventDefault();
    const storage_conditions = lines(programForm.conditions).map(line => { const [id, label, temperature, humidity, light = 'dark'] = line.split('|').map(item => item.trim()); return { id, label, temperature_c: Number(temperature), ...(humidity ? { relative_humidity_percent: Number(humidity) } : {}), light_exposure: light }; });
    await perform(() => projectsAPI.createStabilityProgram(project.id, { name: programForm.name, formulation_version_id: programForm.formulation_version_id, protocol: programForm.protocol, status: 'draft', storage_conditions, timepoints_days: csvNumbers(programForm.timepoints), replicates_per_timepoint: Number(programForm.replicates), parameters: parseLimits(programForm.parameters) }), 'Stability program saved against the exact formulation version.');
    setProgramOpen(false);
  }
  async function recordObservation(event: React.FormEvent) {
    event.preventDefault(); if (!program) return;
    await perform(() => projectsAPI.recordStabilityObservation(project.id, program.id, { laboratory_result_id: observationForm.laboratory_result_id, condition_id: observationForm.condition_id, timepoint_days: Number(observationForm.timepoint_days), replicate: Number(observationForm.replicate) }), 'Laboratory result linked to the stability timepoint.');
    setAnalysis(null); setObservationForm({ laboratory_result_id: '', condition_id: '', timepoint_days: '', replicate: '1' });
  }
  async function loadAnalysis() {
    if (!program) return; setError('');
    try { const response = await projectsAPI.getStabilityAnalysis(project.id, program.id); setAnalysis(response.data.data); }
    catch (cause) { setError(getErrorMessage(cause, 'Stability analysis could not be calculated.')); }
  }
  async function createSpecification(event: React.FormEvent) {
    event.preventDefault();
    await perform(() => projectsAPI.createSpecification(project.id, { name: specForm.name, formulation_version_id: specForm.formulation_version_id, markets: specForm.markets.split(',').map(item => item.trim()).filter(Boolean), effective_date: specForm.effective_date || null, notes: specForm.notes, limits: parseLimits(specForm.limits) }), 'Draft product specification created.');
    setSpecOpen(false);
  }
  async function approveSpecification(event: React.FormEvent) {
    event.preventDefault(); if (!approval.specification_id) return;
    await perform(() => projectsAPI.approveSpecification(project.id, approval.specification_id, { rationale: approval.rationale, evidence_refs: lines(approval.evidence_refs) }), 'Specification approved and locked with its evidence trail.');
    setApproval({ specification_id: '', rationale: '', evidence_refs: '' });
  }

  const programLabs = laboratory.filter(item => item.formulation_version_id === program?.formulation_version_id && !observations.some(observation => observation.laboratory_result_id === item.id));
  const draftSpecifications = specifications.filter(item => item.status === 'draft');
  return <div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-lg font-black text-slate-950">Stability programs & controlled specifications</h3><p className="mt-1 max-w-3xl text-sm text-slate-500">Schedule measurable timepoints, link existing laboratory evidence and preserve every approved release limit.</p></div><div className="flex gap-2"><button type="button" onClick={() => setProgramOpen(!programOpen)} className="primary-button"><Plus className="h-4 w-4"/>New program</button><button type="button" onClick={() => setSpecOpen(!specOpen)} className="secondary-button"><Plus className="h-4 w-4"/>New specification</button></div></div>
    {error && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-900">{error}</div>}
    {programOpen && <form onSubmit={createProgram} className="rounded-2xl border border-sky-200 bg-sky-50/50 p-4"><h4 className="font-black text-slate-950">Controlled stability protocol</h4><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Program name"><input required minLength={3} value={programForm.name} onChange={event => setProgramForm({...programForm, name: event.target.value})}/></Field><Field label="Exact formulation version"><select required value={programForm.formulation_version_id} onChange={event => setProgramForm({...programForm, formulation_version_id: event.target.value})}>{versions.map(version => <option key={version.id} value={version.id}>{version.name} · v{version.version}</option>)}</select></Field><Field label="Protocol" wide><textarea required minLength={10} rows={2} value={programForm.protocol} onChange={event => setProgramForm({...programForm, protocol: event.target.value})}/></Field><Field label="Conditions — id | label | °C | RH% | light" wide><textarea required rows={3} value={programForm.conditions} onChange={event => setProgramForm({...programForm, conditions: event.target.value})}/></Field><Field label="Timepoints in days"><input required value={programForm.timepoints} onChange={event => setProgramForm({...programForm, timepoints: event.target.value})}/></Field><Field label="Replicates per timepoint"><input type="number" min="1" max="20" value={programForm.replicates} onChange={event => setProgramForm({...programForm, replicates: event.target.value})}/></Field><Field label="Parameters — key | label | source | unit | min | max | max baseline change" wide><textarea required rows={4} value={programForm.parameters} onChange={event => setProgramForm({...programForm, parameters: event.target.value})}/></Field></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setProgramOpen(false)} className="secondary-button">Cancel</button><button disabled={busy} className="primary-button">Save stability program</button></div></form>}
    {specOpen && <form onSubmit={createSpecification} className="rounded-2xl border border-violet-200 bg-violet-50/40 p-4"><h4 className="font-black text-slate-950">Versioned finished-product specification</h4><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Specification name"><input required value={specForm.name} onChange={event => setSpecForm({...specForm, name: event.target.value})}/></Field><Field label="Exact formulation version"><select required value={specForm.formulation_version_id} onChange={event => setSpecForm({...specForm, formulation_version_id: event.target.value})}>{versions.map(version => <option key={version.id} value={version.id}>{version.name} · v{version.version}</option>)}</select></Field><Field label="Markets"><input value={specForm.markets} onChange={event => setSpecForm({...specForm, markets: event.target.value})}/></Field><Field label="Effective date"><input type="date" value={specForm.effective_date} onChange={event => setSpecForm({...specForm, effective_date: event.target.value})}/></Field><Field label="Limits — key | label | source | unit | min | max | max change" wide><textarea required rows={4} value={specForm.limits} onChange={event => setSpecForm({...specForm, limits: event.target.value})}/></Field><Field label="Controlled notes" wide><textarea rows={2} value={specForm.notes} onChange={event => setSpecForm({...specForm, notes: event.target.value})}/></Field></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setSpecOpen(false)} className="secondary-button">Cancel</button><button disabled={busy} className="primary-button">Create draft specification</button></div></form>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(20rem,.65fr)]"><section className="space-y-4"><div className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Active program</p><select className="mt-1 min-w-72" value={program?.id || ''} onChange={event => { setProgramId(event.target.value); setAnalysis(null); }}><option value="">Choose a program</option>{programs.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>{program && <><Badge value={program.status}/><button type="button" onClick={() => void loadAnalysis()} className="secondary-button"><Activity className="h-4 w-4"/>Calculate trends</button></>}</div>{program ? <><div className="mt-4 grid gap-2 sm:grid-cols-3"><Metric icon={Thermometer} value={program.storage_conditions.length} label="Conditions"/><Metric icon={Clock3} value={program.timepoints_days.length} label="Timepoints"/><Metric icon={CheckCircle2} value={observations.filter(item => item.program_id === program.id).length} label="Recorded"/></div><form onSubmit={recordObservation} className="mt-5 grid gap-3 border-t border-slate-100 pt-4 md:grid-cols-2"><Field label="Saved laboratory result"><select required value={observationForm.laboratory_result_id} onChange={event => setObservationForm({...observationForm, laboratory_result_id: event.target.value})}><option value="">Choose unlinked evidence</option>{programLabs.map(item => <option key={item.id} value={item.id}>{item.batch_code || item.id} · {new Date(item.tested_at).toLocaleDateString()}</option>)}</select></Field><Field label="Storage condition"><select required value={observationForm.condition_id} onChange={event => setObservationForm({...observationForm, condition_id: event.target.value})}><option value="">Choose condition</option>{program.storage_conditions.map(item => <option key={item.id} value={item.id}>{item.label} · {item.temperature_c} °C</option>)}</select></Field><Field label="Timepoint"><select required value={observationForm.timepoint_days} onChange={event => setObservationForm({...observationForm, timepoint_days: event.target.value})}><option value="">Choose day</option>{program.timepoints_days.map(day => <option key={day} value={day}>Day {day}</option>)}</select></Field><Field label="Replicate"><input type="number" min="1" max={program.replicates_per_timepoint} value={observationForm.replicate} onChange={event => setObservationForm({...observationForm, replicate: event.target.value})}/></Field><div className="md:col-span-2 flex justify-end"><button disabled={busy || !programLabs.length} className="primary-button">Link laboratory evidence</button></div></form></> : <p className="py-10 text-center text-sm text-slate-500">Create a program to begin scheduled stability tracking.</p>}</div>{analysis && <Analysis analysis={analysis}/>}</section>
      <aside className="space-y-4"><div className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-2"><LockKeyhole className="h-5 w-5 text-violet-600"/><h4 className="font-black text-slate-950">Product specifications</h4></div><div className="mt-4 space-y-3">{specifications.length ? specifications.map(item => <SpecificationCard key={item.id} item={item}/>) : <p className="text-sm text-slate-500">No controlled specification yet.</p>}</div></div>{draftSpecifications.length > 0 && <form onSubmit={approveSpecification} className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><h4 className="font-black text-emerald-950">Approve and lock</h4><Field label="Draft specification"><select required value={approval.specification_id} onChange={event => setApproval({...approval, specification_id: event.target.value})}><option value="">Choose draft</option>{draftSpecifications.map(item => <option key={item.id} value={item.id}>{item.name} · v{item.version}</option>)}</select></Field><Field label="Evidence references"><textarea required rows={3} value={approval.evidence_refs} onChange={event => setApproval({...approval, evidence_refs: event.target.value})} placeholder="One laboratory result or decision reference per line"/></Field><Field label="Approval rationale"><textarea required minLength={10} rows={3} value={approval.rationale} onChange={event => setApproval({...approval, rationale: event.target.value})}/></Field><button disabled={busy} className="primary-button mt-3 w-full">Approve immutable specification</button></form>}</aside></div>
  </div>;
}

function Analysis({ analysis }: { analysis: RDStabilityAnalysis }) { return <div className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">Deterministic stability analysis</p><h4 className="mt-1 font-black text-slate-950">{analysis.conclusion}</h4></div><Badge value={analysis.overall_status}/></div><p className="mt-2 text-xs font-semibold text-amber-800">{analysis.extrapolation.reason}</p><div className="mt-4 space-y-4">{analysis.conditions.map(condition => <article key={condition.id} className="rounded-xl bg-slate-50 p-3"><div className="flex items-center justify-between"><strong>{condition.label} · {condition.temperature_c} °C</strong><span className="text-xs text-slate-500">{condition.completion_percent}% complete</span></div><div className="mt-3 overflow-x-auto"><table className="min-w-full text-xs"><thead><tr className="text-left text-slate-500"><th className="py-2">Parameter</th><th>Baseline</th><th>30-day slope</th><th>R²</th><th>First failure</th><th>Status</th></tr></thead><tbody>{condition.parameters.map(parameter => <tr key={parameter.key} className="border-t border-slate-200"><th className="py-2 text-left">{parameter.label}</th><td>{parameter.baseline ?? '—'} {parameter.unit}</td><td>{parameter.trend.slope_per_30_days ?? '—'}</td><td>{parameter.trend.r_squared ?? '—'}</td><td>{parameter.first_observed_failure_day === null ? 'None observed' : `Day ${parameter.first_observed_failure_day}`}</td><td><Badge value={parameter.status}/></td></tr>)}</tbody></table></div></article>)}</div></div>; }
function SpecificationCard({ item }: { item: RDProductSpecification }) { return <article className="rounded-xl bg-slate-50 p-3"><div className="flex items-start justify-between gap-2"><div><strong className="text-sm text-slate-950">{item.name}</strong><p className="mt-1 text-xs text-slate-500">Version {item.version} · {item.limits.length} limits · {item.markets.join(', ') || 'No market'}</p></div><Badge value={item.status}/></div>{item.status === 'approved' && <p className="mt-2 flex items-center gap-1 text-xs font-semibold text-emerald-700"><LockKeyhole className="h-3 w-3"/>Immutable since approval</p>}</article>; }
function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`${wide ? 'md:col-span-2' : ''} block`}><span>{label}</span>{children}</label>; }
function Metric({ icon: Icon, value, label }: { icon: typeof Clock3; value: number; label: string }) { return <div className="rounded-xl bg-slate-50 p-3"><Icon className="h-4 w-4 text-sky-600"/><strong className="mt-2 block text-lg text-slate-950">{value}</strong><span className="text-xs text-slate-500">{label}</span></div>; }
