import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, FileCheck2, Package, Plus, ShieldCheck, Truck } from 'lucide-react';
import { projectsAPI, supplyChainAPI } from '../services/api';
import { getErrorMessage } from '../services/errors';
import type { RDMaterialSpecification, RDPackagingComponent, RDProject, RDSupplier, RDSupplierMaterial } from '../types';
import StatusMessage from './StatusMessage';

type Workspace = { suppliers: RDSupplier[]; supplier_materials: RDSupplierMaterial[]; material_specifications: RDMaterialSpecification[]; packaging_components: RDPackagingComponent[] };
const emptyWorkspace: Workspace = { suppliers: [], supplier_materials: [], material_specifications: [], packaging_components: [] };
const csv = (value: string) => value.split(',').map(item => item.trim()).filter(Boolean);
const lines = (value: string) => value.split('\n').map(item => item.trim()).filter(Boolean);

export default function SupplyChainWorkspace({ project, onRefresh }: { project: RDProject; onRefresh: () => Promise<void> }) {
  const [section, setSection] = useState<'suppliers' | 'documents' | 'packaging'>('suppliers');
  const [workspace, setWorkspace] = useState<Workspace>(emptyWorkspace);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const documents = project.traceability?.documents || []; const configurations = project.traceability?.packaging_configurations || [];
  async function reload() { const response = await supplyChainAPI.getWorkspace(); setWorkspace(response.data.data); }
  useEffect(() => { void reload().catch(cause => setError(getErrorMessage(cause, 'Supply-chain data could not be loaded.'))); }, []);
  async function perform(action: () => Promise<unknown>, success: string, refreshProject = false) {
    setBusy(true); setError(''); setMessage('');
    try { await action(); setMessage(success); await reload(); if (refreshProject) await onRefresh(); }
    catch (cause) { setError(getErrorMessage(cause, 'The controlled record could not be saved.')); }
    finally { setBusy(false); }
  }
  if (project.supply_chain_available === false) return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="eyebrow text-amber-700">Supply chain</p><h3 className="mt-1 font-black text-amber-950">Storage migration required</h3><p className="mt-2 text-sm text-amber-900">Apply the pending supplier, document and packaging migration.</p></div>;
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">Qualified inputs</p><h3 className="mt-1 text-lg font-black text-slate-950">Suppliers, evidence & packaging</h3><p className="mt-1 max-w-3xl text-sm text-slate-500">Connect qualified material facts and immutable documents to a costed package for the exact product version.</p></div><div className="grid grid-cols-3 gap-2 text-center text-xs"><Metric value={workspace.suppliers.length} label="Suppliers"/><Metric value={documents.length} label="Documents"/><Metric value={configurations.length} label="Packages"/></div></div>
    <div className="flex gap-2 overflow-x-auto rounded-2xl bg-slate-50 p-2" role="tablist" aria-label="Supply chain sections">{[
      ['suppliers','Suppliers & materials',Truck],['documents','Documents',FileCheck2],['packaging','Packaging',Package],
    ].map(([key,label,Icon]) => <button key={String(key)} type="button" role="tab" aria-selected={section === key} onClick={() => setSection(key as typeof section)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold ${section === key ? 'bg-white text-sky-700 shadow-sm ring-1 ring-sky-200' : 'text-slate-500 hover:bg-white'}`}><Icon className="h-4 w-4"/>{String(label)}</button>)}</div>
    <StatusMessage error={error} message={message}/>
    {section === 'suppliers' && <Suppliers workspace={workspace} busy={busy} perform={perform}/>} 
    {section === 'documents' && <Documents project={project} workspace={workspace} busy={busy} perform={perform}/>} 
    {section === 'packaging' && <Packaging project={project} workspace={workspace} busy={busy} perform={perform}/>} 
  </div>;
}

function Suppliers({ workspace, busy, perform }: { workspace: Workspace; busy: boolean; perform: (action: () => Promise<unknown>, success: string, refresh?: boolean) => Promise<void> }) {
  const [supplierOpen, setSupplierOpen] = useState(false); const [materialOpen, setMaterialOpen] = useState(false); const [specOpen, setSpecOpen] = useState(false);
  const [supplier, setSupplier] = useState({ name: '', country: 'Algeria', contact_name: '', contact_email: '', certifications: 'ISO 9001, Halal', qualification_score: '0', notes: '' });
  const [material, setMaterial] = useState({ supplier_id: '', material_code: '', name: '', status: 'candidate', price_per_kg: '0', moq_kg: '0', lead_time_days: '0', certifications: '', allergens: '', manufacturing_site: '', notes: '' });
  const [spec, setSpec] = useState({ material_id: '', name: '', limits: 'purity | Purity | % | 99 | 100 | Supplier CoA', notes: '' });
  async function addSupplier(event: React.FormEvent) { event.preventDefault(); await perform(() => supplyChainAPI.createSupplier({ ...supplier, certifications: csv(supplier.certifications), qualification_score: Number(supplier.qualification_score), status: 'prospect' }), 'Supplier registered.'); setSupplierOpen(false); }
  async function addMaterial(event: React.FormEvent) { event.preventDefault(); await perform(() => supplyChainAPI.createMaterial(material.supplier_id, { ...material, supplier_id: undefined, price_per_kg: Number(material.price_per_kg), moq_kg: Number(material.moq_kg), lead_time_days: Number(material.lead_time_days), certifications: csv(material.certifications), allergens: csv(material.allergens), currency: 'DZD' }), 'Supplier material registered.'); setMaterialOpen(false); }
  async function addSpec(event: React.FormEvent) { event.preventDefault(); const limits = lines(spec.limits).map(line => { const [key,label,unit,lower,upper,method=''] = line.split('|').map(value => value.trim()); return { key, label, unit, ...(lower ? { lower: Number(lower) } : {}), ...(upper ? { upper: Number(upper) } : {}), method }; }); await perform(() => supplyChainAPI.createMaterialSpecification(spec.material_id, { name: spec.name, limits, notes: spec.notes }), 'Draft material specification created.'); setSpecOpen(false); }
  return <div className="space-y-5"><Heading title="Qualified supplier directory" text="Qualification is explicit; commercial facts never silently become approved technical specifications." actions={<><button type="button" className="secondary-button" onClick={() => setMaterialOpen(!materialOpen)} disabled={!workspace.suppliers.length}><Plus className="h-4 w-4"/>Material</button><button type="button" className="primary-button" onClick={() => setSupplierOpen(!supplierOpen)}><Plus className="h-4 w-4"/>Supplier</button></>}/>
    {supplierOpen && <form onSubmit={addSupplier} className="form-panel"><Grid><Field label="Supplier name"><input required value={supplier.name} onChange={e => setSupplier({...supplier,name:e.target.value})}/></Field><Field label="Country"><input value={supplier.country} onChange={e => setSupplier({...supplier,country:e.target.value})}/></Field><Field label="Contact"><input value={supplier.contact_name} onChange={e => setSupplier({...supplier,contact_name:e.target.value})}/></Field><Field label="Email"><input type="email" value={supplier.contact_email} onChange={e => setSupplier({...supplier,contact_email:e.target.value})}/></Field><Field label="Certifications"><input value={supplier.certifications} onChange={e => setSupplier({...supplier,certifications:e.target.value})}/></Field><Field label="Initial qualification score"><input type="number" min="0" max="100" value={supplier.qualification_score} onChange={e => setSupplier({...supplier,qualification_score:e.target.value})}/></Field><Field label="Notes" wide><textarea value={supplier.notes} onChange={e => setSupplier({...supplier,notes:e.target.value})}/></Field></Grid><Actions busy={busy} label="Register supplier"/></form>}
    {materialOpen && <form onSubmit={addMaterial} className="form-panel"><Grid><Field label="Supplier"><select required value={material.supplier_id} onChange={e => setMaterial({...material,supplier_id:e.target.value})}><option value="">Choose</option>{workspace.suppliers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Supplier material code"><input required value={material.material_code} onChange={e => setMaterial({...material,material_code:e.target.value})}/></Field><Field label="Material name"><input required value={material.name} onChange={e => setMaterial({...material,name:e.target.value})}/></Field><Field label="Status"><select value={material.status} onChange={e => setMaterial({...material,status:e.target.value})}><option value="candidate">Candidate</option><option value="approved">Approved</option><option value="restricted">Restricted</option></select></Field><Field label="Price / kg (DZD)"><input type="number" min="0" step="any" value={material.price_per_kg} onChange={e => setMaterial({...material,price_per_kg:e.target.value})}/></Field><Field label="MOQ (kg)"><input type="number" min="0" value={material.moq_kg} onChange={e => setMaterial({...material,moq_kg:e.target.value})}/></Field><Field label="Lead time (days)"><input type="number" min="0" value={material.lead_time_days} onChange={e => setMaterial({...material,lead_time_days:e.target.value})}/></Field><Field label="Manufacturing site"><input value={material.manufacturing_site} onChange={e => setMaterial({...material,manufacturing_site:e.target.value})}/></Field><Field label="Certifications"><input value={material.certifications} onChange={e => setMaterial({...material,certifications:e.target.value})}/></Field><Field label="Allergens"><input value={material.allergens} onChange={e => setMaterial({...material,allergens:e.target.value})}/></Field></Grid><Actions busy={busy} label="Register material"/></form>}
    <div className="grid gap-3 lg:grid-cols-2">{workspace.suppliers.map(item => { const materials = workspace.supplier_materials.filter(material => material.supplier_id === item.id); return <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex justify-between gap-3"><div><p className="eyebrow">{item.country || 'Country not set'}</p><h4 className="mt-1 font-black text-slate-950">{item.name}</h4></div><Badge value={item.status}/></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><Mini label="Score" value={`${item.qualification_score}/100`}/><Mini label="Materials" value={materials.length}/><Mini label="Certificates" value={item.certifications.length}/></div>{materials.map(entry => <div key={entry.id} className="mt-3 rounded-xl bg-slate-50 p-3"><div className="flex justify-between"><strong className="text-sm">{entry.name}</strong><Badge value={entry.status}/></div><p className="mt-1 text-xs text-slate-500">{entry.material_code} · {entry.price_per_kg.toLocaleString()} {entry.currency}/kg · lead {entry.lead_time_days} d</p></div>)}</article>; })}</div>
    <Heading title="Controlled material specifications" text="Each revision has measurable limits and an approval state." actions={<button type="button" className="secondary-button" disabled={!workspace.supplier_materials.length} onClick={() => setSpecOpen(!specOpen)}><Plus className="h-4 w-4"/>New specification</button>}/>
    {specOpen && <form onSubmit={addSpec} className="form-panel"><Grid><Field label="Supplier material"><select required value={spec.material_id} onChange={e => setSpec({...spec,material_id:e.target.value})}><option value="">Choose</option>{workspace.supplier_materials.map(item => <option key={item.id} value={item.id}>{item.name} · {item.material_code}</option>)}</select></Field><Field label="Specification name"><input required value={spec.name} onChange={e => setSpec({...spec,name:e.target.value})}/></Field><Field label="Limits — key | label | unit | min | max | method" wide><textarea rows={3} required value={spec.limits} onChange={e => setSpec({...spec,limits:e.target.value})}/></Field><Field label="Notes" wide><textarea value={spec.notes} onChange={e => setSpec({...spec,notes:e.target.value})}/></Field></Grid><Actions busy={busy} label="Create draft"/></form>}
    <div className="space-y-2">{workspace.material_specifications.map(item => <article key={item.id} className="flex flex-col gap-3 rounded-2xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Revision {item.version}</p><h4 className="font-black">{item.name}</h4><p className="text-xs text-slate-500">{item.limits.length} controlled parameter(s)</p></div><div className="flex items-center gap-2"><Badge value={item.status}/>{item.status === 'draft' && <button type="button" className="secondary-button" disabled={busy} onClick={() => void perform(() => supplyChainAPI.approveMaterialSpecification(item.id,{ rationale:'Technical limits reviewed against supplier documentation.', evidence_refs:[`SPEC-${item.id}`] }), 'Material specification approved.')}><ShieldCheck className="h-4 w-4"/>Approve</button>}</div></article>)}</div>
  </div>;
}

function Documents({ project, workspace, busy, perform }: { project: RDProject; workspace: Workspace; busy: boolean; perform: (action: () => Promise<unknown>, success: string, refresh?: boolean) => Promise<void> }) {
  const documents = project.traceability?.documents || []; const versions = project.traceability?.formulations || [];
  const [open,setOpen]=useState(false); const [form,setForm]=useState({ document_type:'technical_data_sheet',title:'',file_name:'',mime_type:'application/pdf',size_bytes:'0',sha256:'',storage_reference:'',source:'',supplier_id:'',supplier_material_id:'',formulation_version_id:'',issued_date:'',expires_date:'',extracted_text:'' });
  async function submit(event:React.FormEvent){event.preventDefault();await perform(()=>projectsAPI.registerDocument(project.id,{...form,size_bytes:Number(form.size_bytes),supplier_id:form.supplier_id||null,supplier_material_id:form.supplier_material_id||null,formulation_version_id:form.formulation_version_id||null,issued_date:form.issued_date||null,expires_date:form.expires_date||null,extraction_status:form.extracted_text?'extracted':'not_requested'}),'Controlled document registered.',true);setOpen(false);}
  return <div className="space-y-4"><Heading title="Controlled document register" text="The immutable checksum identifies the original; technical extraction remains visibly pending until human review." actions={<button type="button" className="primary-button" onClick={()=>setOpen(!open)}><Plus className="h-4 w-4"/>Register document</button>}/>
    {open&&<form onSubmit={submit} className="form-panel"><Grid><Field label="Document type"><select value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}>{['certificate_of_analysis','technical_data_sheet','safety_data_sheet','certificate','audit_report','packaging_drawing','test_report','other'].map(item=><option key={item} value={item}>{item.replaceAll('_',' ')}</option>)}</select></Field><Field label="Title"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="File name"><input required value={form.file_name} onChange={e=>setForm({...form,file_name:e.target.value})}/></Field><Field label="MIME type"><input required value={form.mime_type} onChange={e=>setForm({...form,mime_type:e.target.value})}/></Field><Field label="Immutable SHA-256"><input required minLength={64} maxLength={64} className="font-mono" value={form.sha256} onChange={e=>setForm({...form,sha256:e.target.value.toLowerCase()})}/></Field><Field label="Size (bytes)"><input required type="number" min="0" value={form.size_bytes} onChange={e=>setForm({...form,size_bytes:e.target.value})}/></Field><Field label="Immutable storage reference"><input required placeholder="Supabase Storage path or controlled DMS URL" value={form.storage_reference} onChange={e=>setForm({...form,storage_reference:e.target.value})}/></Field><Field label="Source/provenance"><input value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></Field><Field label="Supplier"><select value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:e.target.value,supplier_material_id:''})}><option value="">None</option>{workspace.suppliers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Supplier material"><select value={form.supplier_material_id} onChange={e=>setForm({...form,supplier_material_id:e.target.value})}><option value="">None</option>{workspace.supplier_materials.filter(item=>!form.supplier_id||item.supplier_id===form.supplier_id).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Exact formulation version"><select value={form.formulation_version_id} onChange={e=>setForm({...form,formulation_version_id:e.target.value})}><option value="">Project-level</option>{versions.map(item=><option key={item.id} value={item.id}>{item.name} · v{item.version}</option>)}</select></Field><Field label="Expiry date"><input type="date" value={form.expires_date} onChange={e=>setForm({...form,expires_date:e.target.value})}/></Field><Field label="OCR/extracted text for review" wide><textarea rows={4} value={form.extracted_text} onChange={e=>setForm({...form,extracted_text:e.target.value})}/></Field></Grid><Actions busy={busy} label="Register immutable original"/></form>}
    {documents.length===0?<Empty icon={FileCheck2} title="No controlled document" text="Register supplier evidence, test reports or packaging drawings with their immutable checksum."/>:<div className="grid gap-3 lg:grid-cols-2">{documents.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><p className="eyebrow">{item.document_type.replaceAll('_',' ')}</p><h4 className="font-black">{item.title}</h4></div><Badge value={item.review_status}/></div><p className="mt-2 truncate font-mono text-[11px] text-slate-500">SHA-256 {item.sha256}</p><p className="mt-2 text-xs text-slate-500">{item.file_name} · {item.size_bytes.toLocaleString()} bytes · extraction {item.extraction_status}</p>{item.review_status==='pending'&&<div className="mt-3 flex gap-2"><button type="button" className="secondary-button" disabled={busy} onClick={()=>void perform(()=>projectsAPI.reviewDocument(project.id,item.id,{outcome:'accepted',review_notes:'Document identity, provenance and extracted technical content reviewed.'}),'Document accepted and locked.',true)}><CheckCircle2 className="h-4 w-4"/>Accept</button><button type="button" className="secondary-button" disabled={busy} onClick={()=>void perform(()=>projectsAPI.reviewDocument(project.id,item.id,{outcome:'rejected',review_notes:'Document rejected after provenance or technical-content review.'}),'Document rejected and locked.',true)}>Reject</button></div>}</article>)}</div>}
  </div>;
}

function Packaging({project,workspace,busy,perform}:{project:RDProject;workspace:Workspace;busy:boolean;perform:(action:()=>Promise<unknown>,success:string,refresh?:boolean)=>Promise<void>}){
  const configurations=project.traceability?.packaging_configurations||[];const versions=project.traceability?.formulations||[];
  const [componentOpen,setComponentOpen]=useState(false);const [configOpen,setConfigOpen]=useState(false);
  const [component,setComponent]=useState({supplier_id:'',code:'',name:'',component_type:'bottle',material:'PET',status:'candidate',capacity_ml:'330',mass_g:'0',recycled_content_percent:'0',unit_cost:'0',food_contact_compliant:false,markets:'DZ',oxygen:'',water:'',light:'',notes:''});
  const [config,setConfig]=useState({formulation_version_id:versions[0]?.id||'',name:'',intended_shelf_life_days:'180',filling_process:'Cold fill',components:'',transport_conditions:'Ambient distribution',notes:''});
  const componentHint=useMemo(()=>workspace.packaging_components.map(item=>`${item.code} | primary_container | 1`).join('\n'),[workspace.packaging_components]);
  async function addComponent(event:React.FormEvent){event.preventDefault();await perform(()=>supplyChainAPI.createPackagingComponent({supplier_id:component.supplier_id||null,code:component.code,name:component.name,component_type:component.component_type,material:component.material,status:component.status,capacity_ml:component.capacity_ml?Number(component.capacity_ml):null,mass_g:Number(component.mass_g),recycled_content_percent:Number(component.recycled_content_percent),unit_cost:Number(component.unit_cost),currency:'DZD',barrier:{...(component.oxygen?{oxygen_transmission_rate_cc_m2_day:Number(component.oxygen)}:{}),...(component.water?{water_vapor_transmission_rate_g_m2_day:Number(component.water)}:{}),...(component.light?{light_transmission_percent:Number(component.light)}:{})},food_contact_compliant:component.food_contact_compliant,markets:csv(component.markets),notes:component.notes}),'Packaging component registered.');setComponentOpen(false);}
  async function addConfig(event:React.FormEvent){event.preventDefault();const componentLines=lines(config.components).map(line=>{const[code,role,quantity]=line.split('|').map(value=>value.trim());return{component_id:workspace.packaging_components.find(item=>item.code===code)?.id||'',role,quantity:Number(quantity)};});await perform(()=>projectsAPI.createPackagingConfiguration(project.id,{...config,intended_shelf_life_days:Number(config.intended_shelf_life_days),components:componentLines,currency:'DZD'}),'Packaging configuration calculated and saved.',true);setConfigOpen(false);}
  return <div className="space-y-5"><Heading title="Packaging component library" text="Supplier cost, mass, recycled content, food-contact status and barrier data stay explicit." actions={<button type="button" className="secondary-button" onClick={()=>setComponentOpen(!componentOpen)}><Plus className="h-4 w-4"/>Component</button>}/>
    {componentOpen&&<form onSubmit={addComponent} className="form-panel"><Grid><Field label="Code"><input required value={component.code} onChange={e=>setComponent({...component,code:e.target.value})}/></Field><Field label="Name"><input required value={component.name} onChange={e=>setComponent({...component,name:e.target.value})}/></Field><Field label="Type"><select value={component.component_type} onChange={e=>setComponent({...component,component_type:e.target.value})}>{['bottle','can','carton','pouch','closure','label','sleeve','tray','case','film','other'].map(item=><option key={item}>{item}</option>)}</select></Field><Field label="Material"><input required value={component.material} onChange={e=>setComponent({...component,material:e.target.value})}/></Field><Field label="Status"><select value={component.status} onChange={e=>setComponent({...component,status:e.target.value})}><option value="candidate">Candidate</option><option value="approved">Approved</option><option value="restricted">Restricted</option></select></Field><Field label="Supplier"><select value={component.supplier_id} onChange={e=>setComponent({...component,supplier_id:e.target.value})}><option value="">None</option>{workspace.suppliers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Capacity (mL)"><input type="number" min="1" value={component.capacity_ml} onChange={e=>setComponent({...component,capacity_ml:e.target.value})}/></Field><Field label="Mass (g)"><input required type="number" min="0" step="any" value={component.mass_g} onChange={e=>setComponent({...component,mass_g:e.target.value})}/></Field><Field label="Unit cost (DZD)"><input required type="number" min="0" step="any" value={component.unit_cost} onChange={e=>setComponent({...component,unit_cost:e.target.value})}/></Field><Field label="Recycled content (%)"><input type="number" min="0" max="100" value={component.recycled_content_percent} onChange={e=>setComponent({...component,recycled_content_percent:e.target.value})}/></Field><Field label="O₂ transmission"><input type="number" min="0" step="any" value={component.oxygen} onChange={e=>setComponent({...component,oxygen:e.target.value})}/></Field><Field label="Light transmission (%)"><input type="number" min="0" max="100" step="any" value={component.light} onChange={e=>setComponent({...component,light:e.target.value})}/></Field><label className="flex items-center gap-2 md:col-span-2"><input type="checkbox" checked={component.food_contact_compliant} onChange={e=>setComponent({...component,food_contact_compliant:e.target.checked})}/><span>Food-contact compliance verified</span></label></Grid><Actions busy={busy} label="Register component"/></form>}
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{workspace.packaging_components.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between"><div><p className="eyebrow">{item.code}</p><h4 className="font-black">{item.name}</h4></div><Badge value={item.status}/></div><p className="mt-2 text-xs text-slate-500">{item.material} · {item.mass_g} g · {item.unit_cost} {item.currency}/unit · {item.recycled_content_percent}% recycled</p></article>)}</div>
    <Heading title="Version-controlled packaging configurations" text="The server recalculates unit cost, pack mass, recycled content and stability coverage before approval." actions={<button type="button" className="primary-button" disabled={!versions.length||!workspace.packaging_components.length} onClick={()=>setConfigOpen(!configOpen)}><Plus className="h-4 w-4"/>New configuration</button>}/>
    {configOpen&&<form onSubmit={addConfig} className="form-panel"><Grid><Field label="Exact formulation version"><select required value={config.formulation_version_id} onChange={e=>setConfig({...config,formulation_version_id:e.target.value})}><option value="">Choose</option>{versions.map(item=><option key={item.id} value={item.id}>{item.name} · v{item.version}</option>)}</select></Field><Field label="Configuration name"><input required value={config.name} onChange={e=>setConfig({...config,name:e.target.value})}/></Field><Field label="Intended shelf life (days)"><input required type="number" min="1" value={config.intended_shelf_life_days} onChange={e=>setConfig({...config,intended_shelf_life_days:e.target.value})}/></Field><Field label="Filling process"><input value={config.filling_process} onChange={e=>setConfig({...config,filling_process:e.target.value})}/></Field><Field label="Components — code | role | quantity" wide><textarea required rows={4} placeholder={componentHint} value={config.components} onChange={e=>setConfig({...config,components:e.target.value})}/></Field><Field label="Transport conditions"><textarea value={config.transport_conditions} onChange={e=>setConfig({...config,transport_conditions:e.target.value})}/></Field><Field label="Notes"><textarea value={config.notes} onChange={e=>setConfig({...config,notes:e.target.value})}/></Field></Grid><Actions busy={busy} label="Calculate and save"/></form>}
    {configurations.length===0?<Empty icon={Package} title="No packaging configuration" text="Build a configuration from qualified components and link it to an exact formulation version."/>:<div className="space-y-3">{configurations.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><p className="eyebrow">Revision {item.version}</p><h4 className="font-black">{item.name}</h4><p className="text-xs text-slate-500">{versionName(project,item.formulation_version_id)}</p></div><Badge value={item.status}/></div><div className="mt-4 grid gap-2 sm:grid-cols-4"><Mini label="Pack cost" value={`${item.analysis.economics.cost_per_sale_unit} ${item.currency}`}/><Mini label="Pack mass" value={`${item.analysis.sustainability.total_packaging_mass_g} g`}/><Mini label="Recycled" value={`${item.analysis.sustainability.recycled_content_percent_by_mass}%`}/><Mini label="Stability" value={`${item.analysis.stability_link.recorded_coverage_days}/${item.intended_shelf_life_days} d`}/></div>{item.analysis.warnings.length>0&&<ul className="mt-3 space-y-1 rounded-xl bg-amber-50 p-3 text-xs text-amber-900">{item.analysis.warnings.map(warning=><li key={warning}>• {warning}</li>)}</ul>}{item.status==='draft'&&<div className="mt-3 flex justify-end"><button type="button" className="secondary-button" disabled={busy} onClick={()=>void perform(()=>projectsAPI.approvePackagingConfiguration(project.id,item.id,{rationale:'Packaging economics, compatibility risks and available stability evidence reviewed.',evidence_refs:[`PACK-${item.id}`],accept_warnings:true}),'Packaging configuration approved and locked.',true)}><ShieldCheck className="h-4 w-4"/>Approve controlled revision</button></div>}</article>)}</div>}
  </div>;
}

function versionName(project:RDProject,id:string){const item=project.traceability?.formulations.find(version=>version.id===id);return item?`${item.name} · v${item.version}`:'Unknown formulation version';}
function Heading({title,text,actions}:{title:string;text:string;actions?:React.ReactNode}){return <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h4 className="font-black text-slate-950">{title}</h4><p className="mt-1 max-w-3xl text-sm text-slate-500">{text}</p></div><div className="flex gap-2">{actions}</div></div>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 md:grid-cols-2">{children}</div>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?'md:col-span-2':''}><span>{label}</span>{children}</label>}
function Actions({busy,label}:{busy:boolean;label:string}){return <div className="mt-4 flex justify-end"><button disabled={busy} className="primary-button">{label}</button></div>}
function Metric({value,label}:{value:number;label:string}){return <div className="min-w-16 rounded-xl bg-slate-50 px-2 py-2"><strong className="block text-lg">{value}</strong><span className="text-slate-500">{label}</span></div>}
function Mini({value,label}:{value:string|number;label:string}){return <div className="rounded-xl bg-slate-50 p-2"><strong className="block text-sm text-slate-900">{value}</strong><span className="text-[10px] text-slate-500">{label}</span></div>}
function Badge({value}:{value:string}){const good=['qualified','approved','accepted'].includes(value);const bad=['rejected','suspended','restricted','expired'].includes(value);return <span className={`h-fit rounded-full px-2 py-1 text-[10px] font-black uppercase ${good?'bg-emerald-100 text-emerald-700':bad?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-700'}`}>{value.replaceAll('_',' ')}</span>}
function Empty({icon:Icon,title,text}:{icon:typeof Package;title:string;text:string}){return <div className="rounded-2xl border border-dashed border-slate-200 py-10 text-center"><Icon className="mx-auto h-8 w-8 text-sky-400"/><h4 className="mt-3 font-black">{title}</h4><p className="mx-auto mt-1 max-w-xl text-sm text-slate-500">{text}</p></div>}
