-- Historical hosted-migration marker.
-- The equivalent idempotent schema is maintained in 20260817141428_initial_schema.sql.
-- This no-op file keeps local and hosted Supabase migration histories aligned.
