-- Historical hosted-migration marker.
-- The equivalent idempotent schema is maintained in 20260817150124_ai_governance.sql.
-- This no-op file keeps local and hosted Supabase migration histories aligned.
