-- Historical hosted-migration marker.
-- The equivalent idempotent schema is maintained in 20260823120000_laboratory_results_feedback.sql.
-- This no-op file keeps local and hosted Supabase migration histories aligned.
