-- Historical hosted-migration marker.
-- The equivalent idempotent schema is maintained in 20260817141804_enforce_tenant_relational_integrity.sql.
-- This no-op file keeps local and hosted Supabase migration histories aligned.
