-- Historical hosted-migration marker.
-- The equivalent idempotent schema is maintained in 20260817141437_request_scoped_transactional_repository.sql.
-- This no-op file keeps local and hosted Supabase migration histories aligned.
